title: Gos Tutorial
author: Sehi L'Yi, Trevor Manz, Qianwen Wang, Nils Gehlenborg
logo: 'images/gosling-logo.png'
html:
  favicon: "images/favicon.ico"
repository:
    url: "https://github.com/gosling-lang/gos-tutorial"
